services:
  watchpuppy:
    image: wuodan/watchpuppy
    volumes:
      - ./input/:/data/input:ro
    command: [
      "watchpuppy",
      "--insert-action", "echo",
      "--delete-action", "echo",
      "/data/input"
    ]