#!/usr/bin/env bash

set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
SCRIPT_NAME=$(basename "$0")

# Set default log level to INFO if LOG_LEVEL is not set
LOG_LEVEL=${LOG_LEVEL:-INFO}

# Log according to LOG_LEVEL
log() {
    local LEVEL=$1
    local MESSAGE=$2

    # Log level precedence mapping
    declare -A LEVELS=( ["DEBUG"]=10 ["INFO"]=20 ["WARNING"]=30 ["ERROR"]=40 ["CRITICAL"]=50 )

    if [ "${LEVELS[$LEVEL]}" -ge "${LEVELS[$LOG_LEVEL]}" ]; then
        echo "$SCRIPT_NAME - $LEVEL - $MESSAGE"
    fi
}

monitor() {
    local LEVEL=$1
    local MESSAGE=$2
    log "INFO" "Starting file watcher on directory: $WATCH_DIR"
    log "INFO" "Process script: $PROCESS_SCRIPT"

    # Monitor the directory for new files and react to close_write events
    inotifywait -m -r -e close_write --format '%w%f' "$WATCH_DIR" | while read -r NEWFILE
    do
        log "INFO" "New file detected: $NEWFILE"

        # Run the process script
        if ! "$PROCESS_SCRIPT" "$NEWFILE"; then
            log "ERROR" "Error executing $PROCESS_SCRIPT with $NEWFILE"
        else
            log "INFO" "Successfully processed $NEWFILE with $PROCESS_SCRIPT"
        fi
    done
}

# Check if the filesystem type supports inotify
check_inotify_support() {
  localh fs_type=$(stat -f -c %T "$WATCH_DIR")

  # These file systems do not support inotify
  if [[ "$FS_TYPE" == "v9fs" || "$FS_TYPE" == "fuseblk" || "$FS_TYPE" == "nfs" || "$FS_TYPE" == "cifs" || "$FS_TYPE" == "smbfs" || "$FS_TYPE" == "overlayfs" ]]; then
      log "DEBUG" "File system $FS_TYPE does not support inotify. Switching to Python polling."
      return 1
  else
      log "DEBUG" "File system $FS_TYPE supports inotify. Using inotifywait."
      return
  fi
}

# Check if exactly two arguments are provided
if [ $# -ne 2 ]; then
    log "ERROR" "Usage: $0 /path/to/directory /path/to/process-script"
    exit 1
fi

WATCH_DIR="$1"
PROCESS_SCRIPT="$2"

if check_inotify_support; then
    monitor
else
    # with exec the python process replaces the shell process as main process.
    exec python3 /path/to/watchpuppy.py "$WATCH_DIR" "$PROCESS_SCRIPT"
fi